package workshop.akbolatss.tagsnews.repositories.source;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import workshop.akbolatss.tagsnews.repositories.source.RssFeedItem;
import workshop.akbolatss.tagsnews.repositories.source.RssSource;
import workshop.akbolatss.tagsnews.repositories.source.ReminderItem;

import workshop.akbolatss.tagsnews.repositories.source.RssFeedItemDao;
import workshop.akbolatss.tagsnews.repositories.source.RssSourceDao;
import workshop.akbolatss.tagsnews.repositories.source.ReminderItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig rssFeedItemDaoConfig;
    private final DaoConfig rssSourceDaoConfig;
    private final DaoConfig reminderItemDaoConfig;

    private final RssFeedItemDao rssFeedItemDao;
    private final RssSourceDao rssSourceDao;
    private final ReminderItemDao reminderItemDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        rssFeedItemDaoConfig = daoConfigMap.get(RssFeedItemDao.class).clone();
        rssFeedItemDaoConfig.initIdentityScope(type);

        rssSourceDaoConfig = daoConfigMap.get(RssSourceDao.class).clone();
        rssSourceDaoConfig.initIdentityScope(type);

        reminderItemDaoConfig = daoConfigMap.get(ReminderItemDao.class).clone();
        reminderItemDaoConfig.initIdentityScope(type);

        rssFeedItemDao = new RssFeedItemDao(rssFeedItemDaoConfig, this);
        rssSourceDao = new RssSourceDao(rssSourceDaoConfig, this);
        reminderItemDao = new ReminderItemDao(reminderItemDaoConfig, this);

        registerDao(RssFeedItem.class, rssFeedItemDao);
        registerDao(RssSource.class, rssSourceDao);
        registerDao(ReminderItem.class, reminderItemDao);
    }
    
    public void clear() {
        rssFeedItemDaoConfig.clearIdentityScope();
        rssSourceDaoConfig.clearIdentityScope();
        reminderItemDaoConfig.clearIdentityScope();
    }

    public RssFeedItemDao getRssFeedItemDao() {
        return rssFeedItemDao;
    }

    public RssSourceDao getRssSourceDao() {
        return rssSourceDao;
    }

    public ReminderItemDao getReminderItemDao() {
        return reminderItemDao;
    }

}
