package workshop.akbolatss.tagsnews.repositories.source;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "REMINDER_ITEM".
 */
@Entity
public class ReminderItem {

    @Id(autoincrement = true)
    private Long id;
    private Integer requestCode;
    private Boolean isActive;
    private Integer hour;
    private Integer minute;
    private String PM_AM;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated(hash = 499086432)
    public ReminderItem() {
    }

    public ReminderItem(Long id) {
        this.id = id;
    }

    @Generated(hash = 399403805)
    public ReminderItem(Long id, Integer requestCode, Boolean isActive, Integer hour, Integer minute, String PM_AM) {
        this.id = id;
        this.requestCode = requestCode;
        this.isActive = isActive;
        this.hour = hour;
        this.minute = minute;
        this.PM_AM = PM_AM;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getRequestCode() {
        return requestCode;
    }

    public void setRequestCode(Integer requestCode) {
        this.requestCode = requestCode;
    }

    public Boolean getIsActive() {
        return isActive;
    }

    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    public Integer getHour() {
        return hour;
    }

    public void setHour(Integer hour) {
        this.hour = hour;
    }

    public Integer getMinute() {
        return minute;
    }

    public void setMinute(Integer minute) {
        this.minute = minute;
    }

    public String getPM_AM() {
        return PM_AM;
    }

    public void setPM_AM(String PM_AM) {
        this.PM_AM = PM_AM;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
