package workshop.akbolatss.tagsnews.repositories.source;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "RSS_SOURCE".
 */
@Entity
public class RssSource {

    @Id(autoincrement = true)
    private Long id;
    private String source_name;
    private String source_description;
    private String source_link;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated(hash = 1330183901)
    public RssSource() {
    }

    public RssSource(Long id) {
        this.id = id;
    }

    @Generated(hash = 2042051967)
    public RssSource(Long id, String source_name, String source_description, String source_link) {
        this.id = id;
        this.source_name = source_name;
        this.source_description = source_description;
        this.source_link = source_link;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSource_name() {
        return source_name;
    }

    public void setSource_name(String source_name) {
        this.source_name = source_name;
    }

    public String getSource_description() {
        return source_description;
    }

    public void setSource_description(String source_description) {
        this.source_description = source_description;
    }

    public String getSource_link() {
        return source_link;
    }

    public void setSource_link(String source_link) {
        this.source_link = source_link;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
