package workshop.akbolatss.tagsnews.repositories.source;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "RSS_SOURCE".
*/
public class RssSourceDao extends AbstractDao<RssSource, Long> {

    public static final String TABLENAME = "RSS_SOURCE";

    /**
     * Properties of entity RssSource.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Source_name = new Property(1, String.class, "source_name", false, "SOURCE_NAME");
        public final static Property Source_description = new Property(2, String.class, "source_description", false, "SOURCE_DESCRIPTION");
        public final static Property Source_link = new Property(3, String.class, "source_link", false, "SOURCE_LINK");
    }


    public RssSourceDao(DaoConfig config) {
        super(config);
    }
    
    public RssSourceDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"RSS_SOURCE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"SOURCE_NAME\" TEXT," + // 1: source_name
                "\"SOURCE_DESCRIPTION\" TEXT," + // 2: source_description
                "\"SOURCE_LINK\" TEXT);"); // 3: source_link
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"RSS_SOURCE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, RssSource entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String source_name = entity.getSource_name();
        if (source_name != null) {
            stmt.bindString(2, source_name);
        }
 
        String source_description = entity.getSource_description();
        if (source_description != null) {
            stmt.bindString(3, source_description);
        }
 
        String source_link = entity.getSource_link();
        if (source_link != null) {
            stmt.bindString(4, source_link);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, RssSource entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String source_name = entity.getSource_name();
        if (source_name != null) {
            stmt.bindString(2, source_name);
        }
 
        String source_description = entity.getSource_description();
        if (source_description != null) {
            stmt.bindString(3, source_description);
        }
 
        String source_link = entity.getSource_link();
        if (source_link != null) {
            stmt.bindString(4, source_link);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public RssSource readEntity(Cursor cursor, int offset) {
        RssSource entity = new RssSource( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // source_name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // source_description
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // source_link
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, RssSource entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSource_name(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setSource_description(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSource_link(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(RssSource entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(RssSource entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(RssSource entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
